### ISSUE TITLE
Can't get the button to show

### ISSUE THREAD

**Issue by mengqing** [mattmilburn/strapi-plugin-preview-button#19]
The button is not showing, I have an article type, and I have added the following to the plugins file

```
module.exports = ({ env }) => ({
  ...,
  "preview-button": {
    enabled: true,
    config: {
      contentTypes: [
        {
          uid: "api::article.article",
          targetField: "slug",
          draft: {
            query: {
              type: "article",
            },
          },
          published: {
            basePath: "articles",
          },
        },
      ],
    },
  },
  ...,
});
```

Is there anything else I'm missing?

**Comment by shaunpearce** [comment]
For me updating `strapi` to the latest 4.1.8 and `strapi-plugin-preview-button` to the latest 0.3.1, deleting my cache, node-modules and package-lock and doing `npm install` again + `npm run build` did the trick.

**Comment by mattmilburn** [comment]
@mengqing Are you still having this issue after updating Strapi and the preview button plugin to their latest versions?

**Comment by dewil-official** [comment]
Just had the same problem, solved by fixing the `uid` field. Previously I had `api::article` (based on my assumptions) but after searching, I found the correct format in the URL of the admin panel: `api::article.article`

**Comment by Jasonizl** [comment]
I too have the problem not being able to see the button after adding it to the package.json and adding the secrets. Is there anything more needed to be done or am I missing something?

I see some code snippet like the author here where the "preview-button" is being exported - but I have no clue where I would put this even. Any help would be appreciated.

**Comment by KoTTi97** [comment]
I had the same Issue today. I followed @shaunpearce's steps and additionally deleted the browser's cache (hard reset). The preview button then showed up

**Comment by Jasonizl** [comment]
Still have the same issue sadly. I also saw that there are 4 unmet dependencies when doing a `yarn install`.

> warning " > strapi-plugin-preview-button@0.3.4" has unmet peer dependency "@strapi/design-system@^1.1.0".
> warning " > strapi-plugin-preview-button@0.3.4" has unmet peer dependency "@strapi/helper-plugin@^4.1.10".
> warning " > strapi-plugin-preview-button@0.3.4" has unmet peer dependency "@strapi/icons@^1.1.0".
> warning " > strapi-plugin-preview-button@0.3.4" has unmet peer dependency "@strapi/utils@^4.1.10".

I added them manually via. `yarn add ...` but this also didn't resolve the issue.

**Comment by Zharkan** [comment]
When I first started playing with plugins I made a huge mistake, I created a config/plugin.js but I missed the "s" at the end of plugin"s". Maybe this your case too ?
You need to put the plugin's config in config/plugins.js.
